In [2]:
# prod.ms
# 성능평가지표들, 오차행렬, f1 score roc auc에 대해서 궁금합니다

-  정확도(Accuracy)
-  오차행렬(Confusion Matrix)
-  정밀도(Precision)
-  재현율(Recall)
-  F1 스코어
-  ROC AUC


-  prod.sam
-  Pca
1) 차원수를 많이 살려둔다고 해서 항상 정확도가 높아지는 건 아니다 (쓸 데 없는 데이터를 잘 버리면 오히려 정확도가 올라갈 수 있으니까)

2) 데이터가 많을수록 (즉, 차원 축소를 덜 할수록) 설명할 수 있는 범위가 넓어지니까 차원수를 많이 살려둘수록 설명력은 높아진다.

이렇게 이해해면 맞는지 궁금해요 !

In [4]:
# prod.st
# 구조 재배열 해줄때 numpy.reshape 함수 사용하는 것, 
# reshape에서 -1의 의미에 대해서 설명해주세요

In [5]:
import numpy as np

In [7]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a.shape, b.shape

((12,), (3, 4))

In [14]:
c = np.arange(12).reshape(-1,3)
c
c.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
from sklearn.datasets import load_iris
iris = load_iris()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
msg2 = ['I work at google', 'I google at work']

In [24]:
cvect12 = CountVectorizer(ngram_range=1)

In [26]:
m = cvect12.fit_transform(msg2).toarray()
m

TypeError: cannot unpack non-iterable int object