# 데이터 전처리

### 1. 레이블 인코딩

In [2]:
from sklearn.preprocessing import LabelEncoder


In [3]:
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [4]:
# 레이블 인코더 객체 생성
le = LabelEncoder()

In [5]:
# 학습 데이터를 훑어 봄
le.fit(items)

LabelEncoder()

In [7]:
# 인코딩 실행  # 트랜스폼 열벡터 처리
labels = le.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [9]:
# 실전에서는 
le2 = LabelEncoder()
labels = le2.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [16]:
# 고수들은 le2라는 변수를 만들이유가 전혀 없어
labels = LabelEncoder().fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [20]:
# method Chaining
s = ' A quick brown fox '
s.lower().lstrip().rstrip().replace("a", "the").replace('fox', 'wolf').split()
# 메소드가 꼬리에 꼬리를 물고 꼬꼬 무. 

['the', 'quick', 'brown', 'wolf']

In [21]:
le2.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3])

array(['전자렌지', '컴퓨터', '믹서', 'TV', '냉장고', '냉장고', '선풍기', '선풍기'], dtype='<U4')

In [ ]:
# one-hot incoding 은 머신러닝에서는 하용하지 않으나 신경망 .딥 러닝에서는 사용 '
# 오늘은 개념만 

In [ ]:
데이터 인코딩
 원-핫(One-Hot) 인코딩
from sklearn.preprocessing import OneHotEncoder
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels.shape
# 2차원 데이터로 변환
labels = labels.reshape(-1,1)
labels.shape
# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터 차원:', oh_labels.shape)
print('원-핫 인코딩 데이터:\n', oh_labels.toarray())

### 2. one-hot encoding

In [23]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [24]:
oh_labels = encoder.fit_transform(items)
oh_labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [27]:
oh_labels = labels.reshape(-1,1)
oh_labels.shape

(8, 1)

In [28]:
# 위에정리 
# reshape 공부

In [29]:
import numpy as np
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [30]:
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [31]:
a.reshape(2, -1, 4)
# 3c차원 데이터 세팅 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### 3. 표준화 (Standardization) - 표준 정규분포로 변환
- 피쳐 스케일링 정규화 


In [36]:
from sklearn.datasets import load_iris
iris = load_iris()

In [41]:
import pandas as pd
df=pd.DataFrame(iris.data, columns=iris.feature_names)
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [44]:
from sklearn.preprocessing import StandardScaler
# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출. 
scaler.fit(iris.data)
iris_std = scaler.transform(iris.data)

In [46]:
df2 = pd.DataFrame(iris_std, columns=iris.feature_names)
df2.describe()


sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.690315e-15     -1.842970e-15      -1.698641e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)  
count      1.500000e+02  
mean      -1.409243e-15  
std        1.003350e+00  
min       -1.447076e+00  
25%       -1.183812e+00  
50%        1.325097e-01  
75%        7.906707e-01  
max        1.712096e+00

* Logistic Regression 으로 분류

In [48]:
# 왜 오류나유?
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression()
lrc.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)


In [49]:
# 표준 정규분포로 변환된 데이터로 학습하면 에러가 발생하지 않음
X_train, X_test, y_train, y_test = train_test_split(
    iris_std, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)

lrc = LogisticRegression()
lrc.fit(X_train, y_train)

LogisticRegression()

In [50]:
lrc.score(X_test, y_test)

0.9

In [51]:
# 회귀 풀수있는 방법 여러가지 있어 # 선형회귀의 경우 

### 4. 정규화 (Normalization) - 0~1사이의 값으로 변환

In [52]:
from sklearn.preprocessing import MinMaxScaler
iris_mm = MinMaxScaler().fit_transform(iris.data)

In [53]:
df3 = pd.DataFrame(iris_mm, columns=iris.feature_names)
df3.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000

In [54]:
# 정규화로 바꿔도 위 코드 그래도 써도 되

X_train, X_test, y_train, y_test = train_test_split(
    iris_mm, iris.target, stratify=iris.target, test_size=0.2, random_state=2021
)

lrc = LogisticRegression()
lrc.fit(X_train, y_train)
lrc.score(X_test, y_test)

0.9

In [ ]:
 StandardScaler 적용
iris = load_iris()
from sklearn.preprocessing import StandardScaler
# StandardScaler객체 생성
scaler = StandardScaler()
# StandardScaler 로 데이터 셋 변환. fit( ) 과 transform( ) 호출. 
scaler.fit(iris.data)
iris_std = scaler.transform(iris.data)
# 데이터프레임으로 만들어 결과 확인
df_std = pd.DataFrame(i