# 평가

### 1. MNIST 손글씨 - is it seven?

In [1]:
import numpy as np
import pandas as pd 
from sklearn.datasets import load_digits

In [6]:
digits = load_digits()
digits.data.shape   # 쉐입은 튜플로 반환되는 것 기억해. 용재씨 질문하고도 겹치고. 

(1797, 64)

In [7]:
digits.data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [8]:
# 문제가 'Is it seven ?' 이므로 타켓 값이 7이면 1, 나머지는 0
X = digits.data
y = (digits.target == 7).astype(int)  # 트루폴스로 나오는 값이 0 , 1 로 변경

In [9]:
y[:5]

array([0, 0, 0, 0, 0])

In [17]:
np.unique(y, return_counts=True)

(array([0, 1]), array([1618,  179], dtype=int64))

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, random_state=2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape


((1347, 64), (450, 64), (1347,), (450,))

* SVM으로 학습 및 평가

In [18]:
from sklearn.svm import SVC
svc = SVC(random_state = 2021)
svc.fit(X_train, y_train)
pred_sv = svc.predict(X_test)
svc.score(X_test, y_test)
# 정확도 굉장히 높아 .

0.9977777777777778

* 엉터리 분류기로 학습 / 예측 / 평가

In [21]:
from sklearn.base import BaseEstimator

class MyClassifier(BaseEstimator):
    def fit(self, X, y):
        pass
    def predict(self, X):  # 무조건 0을 반환 멍청이 분류기 
        return np.zeros(X.shape[0])    #쉐입 튜플이용 행수 받아내는 것 꼭 연습!!      
         

In [22]:
my_clf = MyClassifier()
my_clf.fit(X_train, y_train)
pred_my = my_clf.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred_my)
# 멍청이 분류기 정확도 90퍼 한쪽으로 편중된 데이터에는 정확도가 의미가 없어
# 모델 성능 평가시 정확도 말고 다른것을 써두는 것이 좋다. 

0.9

In [25]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score
confusion_matrix(y_test, pred_sv)

array([[404,   1],
       [  0,  45]], dtype=int64)

In [26]:
precision_score(y_test, pred_sv), recall_score(y_test, pred_sv)
# 재현율을 100퍼나 나온다.

(0.9782608695652174, 1.0)

In [27]:
confusion_matrix(y_test, pred_my)

array([[405,   0],
       [ 45,   0]], dtype=int64)

In [28]:
precision_score(y_test, pred_my), recall_score(y_test, pred_my)
# worrning 뜻이 뭐니???

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.0, 0.0)

# 지금부터 알쏭달쏭한 컨퓨전 매트릭스의 세계로 초대를 하겠습니다

In [ ]:
# 안가고 싶어.. 오차행렬 기억하려고 애쓰지 마. 


In [ ]:
from sklearn.metrics import fi_score
