Bag of Words 

1. count Vectorizer

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
# CountVectorizer 클래스로 되어 있어. 객체를 생성하고 사용해야 해() 
# 보통 말뭉치라고 이야기하는 corpus , 리스트로 넣어줘야해
corpus = ['Grow your data science skills by competing in our exciting competitions.']

In [9]:
# 클래스 쓰고 싶으면 객체 생성해야 
cvect = CountVectorizer()
cvect.get_params()
# 클래스 이기에 하이터 파라메터 있어. 

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [16]:
output = cvect.fit_transform(corpus)
# print(output)
output

<1x11 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [17]:
output.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [18]:
cvect.vocabulary_ 
# 알파벳 순서로 소팅 됨. 

{'grow': 5,
 'your': 10,
 'data': 3,
 'science': 8,
 'skills': 9,
 'by': 0,
 'competing': 1,
 'in': 6,
 'our': 7,
 'exciting': 4,
 'competitions': 2}

- 불용어(Stopwords) 제거

In [19]:
# 자체제거 
cvect = CountVectorizer(stop_words=['by', 'in', 'our'])
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1 1]]
{'grow': 4, 'your': 7, 'data': 2, 'science': 5, 'skills': 6, 'competing': 0, 'exciting': 3, 'competitions': 1}


In [20]:
# scikit - learn 에서 제공하는 불용어 사용
# your 유어까지 지워진것을 알 수 있다.
cvect = CountVectorizer(stop_words='english')
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'grow': 4, 'data': 2, 'science': 5, 'skills': 6, 'competing': 0, 'exciting': 3, 'competitions': 1}


In [22]:
# 최초실행시 nltk 작업을 한 경우에는 punkt, stopwords 모듈을 다운로드 받으세요.
# import nltk
# nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [24]:
# NLTK 에서 제공하는 불용어 사용 
from nltk.corpus import stopwords
sw = stopwords.words('english')
len(sw), type(sw)

(179, list)

In [25]:
# nltk제공 토크나이저 불용어 처리 your by in our 등 처리
cvect = CountVectorizer(stop_words=sw)
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'grow': 4, 'data': 2, 'science': 5, 'skills': 6, 'competing': 0, 'exciting': 3, 'competitions': 1}


In [32]:
# 딕셔너리에서 반복문???  # 딕셔너리.keys() 써줄것. 이전파이썬 버전인데 알고 있어야
voca = cvect.vocabulary_
for key in voca.keys():
    print(key, voca[key])

grow 4
data 2
science 5
skills 6
competing 0
exciting 3
competitions 1


In [33]:
for key, value in voca.items():
    print(key, value)


grow 4
data 2
science 5
skills 6
competing 0
exciting 3
competitions 1


In [41]:
# 인덱스로 5를 주면 리턴 사이언스값
def get_word(index, voca):
    for key in voca:
        if voca[key] == index:
            return key

In [42]:
get_word(5, cvect.vocabulary_)

'science'

In [43]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key
get_word(5, cvect.vocabulary_)

'science'

In [ ]:
# 먼저 다루어야 할 n-gram 
# 연속적인 n개의 토큰으로 성된 단어. 