# 넘파이 연습문제 풀기  ,자료 21p

In [1]:
import numpy as np
import pandas as pd

## Q1. 행렬만들기

In [2]:
np.arange(10,81,10).reshape(2,4)
# np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## Q2. Indexing, Slicing

In [3]:
# 2. 주어진 행렬에서 새끼번호 문제
# 멍청하게 이걸 만들고 있네 .흙흙
m = np.array([
    [0,1,2,3,4],
    [5,6,7,8,9],
    [10,11,12,13,14]
])
#  np.arange(0,15).reshape(3,5)

In [4]:
# 1) 7은 2D 매트릭스의 2행 3열 (2,3)
m[1,2]

7

In [5]:
# 2) 14는 (3,5)
m[2,4]

14

In [6]:
# 3) 배열 [6,7], 2행의 2,3열
m[1, 1:3]

array([6, 7])

In [7]:
# 4)배열 [7,12]  2행,3행 의 3열
m[1:3, 2]

array([ 7, 12])

In [8]:
# 5)배열 [3,4], [8,9] #3:5에서 5자리에 -1음수 인덱스 쓰고 싶으면?
# m[:2, 3:5]
m[:-1, 3:]

array([[3, 4],
       [8, 9]])

## Q3 Boolean indexing


In [9]:
# 3번 문제 
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
# 3.1) 3의 배수를 찾아라? #3의 배수
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [11]:
# 3.2) 4로 나누면 1이 남는수
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [12]:
# 3.3)  3으로 나누면 나누어 지고 4로 나누면 1이 남는 수 ? 교집합 찾기
f[(f % 3 == 0) &(f % 4 == 1)]

array([9])

##. Q4 대각선 행렬

In [13]:
# 한줄로 쓰는 답 #샘과 함께
# 추후 정리. 최종적으로 2*m1 + 3*m2

In [14]:
# 4
m1 = np.eye(N=5,M=5, dtype=np.int8)
m1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [15]:
m2 = np.eye(N=5,M=5,k=-1, dtype=np.int8)
m2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

In [16]:
dab = m1+m1+(3*m2)
dab

array([[2, 0, 0, 0, 0],
       [3, 2, 0, 0, 0],
       [0, 3, 2, 0, 0],
       [0, 0, 3, 2, 0],
       [0, 0, 0, 3, 2]], dtype=int8)

## Q5. 랜덤 실수 행렬 uniform

In [17]:
# 5. 0에서 10까지 랜덤 실수값으로 이루어진 ..근데 유니폼을 쓰는게 답인가...?
np.random.seed(seed=2021)
a = np.random.uniform(0,10,30).reshape(5,6).round(4)


In [18]:
# 전체의 최대값
a.max()
# 각행의 합
np.sum(a, axis=1)
# 각 행의 최대 값
np.max(a, axis=1)  #다른 버전  a.max(axis=1)
# 각 열의 평균
np.mean(a, axis=0)
# 각 열의 최솟값
np.min(a, axis=0)


array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

## Q6. sorting

In [19]:
score = np.array([
    [1,2,3,4],
    [46,99,100,71],
    [81,59,90,100]    
])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [20]:
# 영어성적으로 정렬. 통상적으로는 내림차순 정렬일것. 
np.sort(score[1])[::-1]

array([100,  99,  71,  46])

In [21]:
# 영어성적 내림차순의 index값
indices = np.argsort(score[1])[::-1]
indices

array([2, 1, 3, 0], dtype=int64)

In [22]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
score[:, indices]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [23]:
# 한 줄로 표현 # score[1]이 영어성적 로우
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

## Q7. 주사위 100번

In [24]:
# 7.1  주사위를 100던 전지는 가상실험.  ?
np.random.seed(2021)
# dice = np.random.binomial(1,7.100)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [25]:
np.mean(dice)

3.7

In [26]:
np.unique(dice, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [27]:
# 튜플 언패킹 타입 확인용
type(np.unique(dice, return_counts=True))

# () 튜플타입의 자료를 아래셀의 첫줄처럼 언패킹해서 쓰는 것이 가능함. 
# type(unique, counts)???  튜플 언패킹 타입 확인하는 방법은???

tuple

In [28]:
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

In [29]:
import pandas as pd
s = pd.Series(counts, index=unique)
s

1     8
2    21
3    19
4    18
5    13
6    21
dtype: int64

#### Q7 type2  6바이6 36으로도 제시해보기

In [30]:
np.random.seed(2021)
dice = np.random.randint(1,7,36)
np.mean(dice)
# 보자마자, 랜덤시드라서 값이 큰 의미가 없다는 것을 알았다.
# 원래 1이나올 확률과 2, 3, 4, ,5, 6 이각각 나올 확률 등을 알아보고자 했는데. 
# 랜덤값이라 의미없어. 

3.7777777777777777

## Q8. 정규분포

In [31]:
# 8.1 가격 10000원 주식. 일간 수익률  # 틀린버전.

stock = np.random.randn(250)
100*stock

array([  79.21244851, -185.78245596, -197.34812894,    0.51221452,
        161.90288933,   70.71843469,  258.9043921 ,  127.66717632,
       -142.00818247, -180.13384822,   75.72279605,  -61.77697342,
        -63.74781338,  -75.02755898,  131.07878694,   64.96526788,
        147.36359443, -191.19297147,   78.67667093, -131.71455398,
       -211.5988457 ,  -19.84625058,  -38.39659531,    7.8282756 ,
        -28.99995125,   69.05056918,  -54.30006902,  -98.33216913,
        -10.34863448,   60.80479187,   96.81796441, -140.6564373 ,
        -46.05780242,   94.97217922,   -9.73721106, -145.3753771 ,
         84.11052974,  -99.7719838 ,   15.48366507,  -66.45584119,
         49.02578138, -100.42170245,  126.56049002,  118.40383789,
       -237.27946268,   70.41781199,   98.19220531, -176.78041092,
       -161.58024188,  -50.65048914,   41.99430974,  132.82802683,
          6.17803493,  158.16880395,   27.37285679,  -42.87902836,
        -94.13975772,  250.91333509,  -62.5246668 , -172.52855

In [32]:
# 쌤과 함께 # 5개만 먼저 테스트 # 0.01은 어디서 오지? 기대값이 0퍼인데..ㅇ

np.random.seed(2021)
rate = np.random.randn(5) * 0.01
rate

array([ 0.01488609,  0.00676011, -0.00418451, -0.00806521,  0.00555876])

In [33]:
price = 10000
for i in range(5):
    price += price * rate[i]    # price = price * (1 + rate[i])
    price = np.round(price)     # 국내주식 소숫점 없으니 반올림
    print(int(price), end=' ')

10149 10218 10175 10093 10149 

In [34]:
# 250개로 확장 
np.random.seed(2021)
rate = np.random.randn(250) * 0.01

price = 10000
price_list= [10000]                         # 초기값 없이 10000부터 더해져도 무관
for i in range(250):
    price = price_list[i] * ( 1 + rate[i])     # price = price * 
    price = np.round(price)                 # 국내주식 소숫점 없으니 반올림
    price_list.append(int(price))

price_list[:10]

[10000, 10149, 10218, 10175, 10093, 10149, 10077, 10191, 10257, 10268]

In [35]:
# empty # C 방식의 , 리스트에 어펜드 사용하기 전 방식연습
np.random.seed(2021)
rate = np.random.randn(250) * 0.01

price_array = np.empty(251, int)          # C 방식의 공간창출
price_array[0] = 10000                      
for i in range(250):
    price = price_array[i] * ( 1 + rate[i])  # price = price * 
    price = np.round(price)                 # 국내주식 소숫점 없으니 반올림
    price_array[i+1] = int(price)

price_array[:10]

array([10000, 10149, 10218, 10175, 10093, 10149, 10077, 10191, 10257,
       10268])