In [ ]:
# 제목 11.Series.ipynb
# 4:33 힘빠진다..

pandas 란 

엑셀, dBMS 등 테이블을 다루는 패키지
피벗테이블 잘 해야. (생산성 겁나 향상)


- 데이터분석에 가장많이 사용
- 열과 행으로 구성된 테이블 형태의 데이터를 주로 다룸
- series 클래스와, DAtaFrame 클래스로 구성
- 사용하는 방법이 매우 다양 & 어려워 데이터 분석 동안 계속 배워야


피벗테이블, join 중요한데, 판다스에서만 어렵지 다른 곳에서는 이미 이용중이라 꼭 익혀야 하는것. 




In [1]:
import numpy as np
import pandas as pd

In [5]:
# 시리즈 생성
s = pd.Series([9904312, 3448737, 2890451, 2466052],
index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [6]:
s[0], s['서울']

(9904312, 9904312)

In [7]:
s[1:3]

부산    3448737
인천    2890451
dtype: int64

In [8]:
s['서울':'인천']  #제목 인덱싱 가능하다

서울    9904312
부산    3448737
인천    2890451
dtype: int64

In [11]:
# 불리언 인덱싱 # 필터링 가능
s [s > 3000000]

서울    9904312
부산    3448737
dtype: int64

In [13]:
d = s/1000000
d

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
dtype: float64

In [15]:
# 딕셔너리로 시리즈 만들기
cities = {'서울':9631482, '부산':3393191, '인천':2632035, '대전':1490158}
s2 = pd.Series(cities)
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [17]:
# 인덱스 기반 연산
ds = s-s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

- 시리즈 속성

In [20]:
# 시리즈 속성과 메소드
s.values            # numpy array


array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [22]:
s.index
# 아래 결과는 리스트는 아니며, like list다. 리스트 비스무리한 놈 / 타입은 판다스의 객체 정도인데(맞는표현?)
type(s.index)

pandas.core.indexes.base.Index

In [26]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [32]:
dice = pd.Series(dice)


In [33]:
# 고유한 값 
dice.unique()

array([5, 6, 2, 1, 4, 3])

In [34]:
# 고유한 값의 개수
dice.nunique()

6

In [35]:
# 고유한 값 (카테고리)별 개수 #################33*******************중요중요
dice.value_counts()

2    21
6    21
3    19
4    18
5    13
1     8
dtype: int64

In [36]:
# 합, 평균, 최대, 최소, 표준편차
dice.sum(), dice.mean(), dice.max(), dice.min(), dice.std() 

(370, 3.7, 6, 1, 1.6298974374376005)

In [37]:
# 요약통계
dice.describe()

count    100.000000
mean       3.700000
std        1.629897
min        1.000000
25%        2.000000
50%        4.000000
75%        5.000000
max        6.000000
dtype: float64

In [38]:
# 정렬
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [39]:
s.sort_values()

대구    2466052
인천    2890451
부산    3448737
서울    9904312
dtype: int64

In [41]:
s.sort_values(ascending=False)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [42]:
s.sort_values()[::-1]

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [43]:
s.sort_index()

대구    2466052
부산    3448737
서울    9904312
인천    2890451
dtype: int64

In [ ]:
# 26페이지까지 연습함. 

In [ ]:
# 1223 판다스 이어서 27p

Pandas _ DataFrame

In [ ]:
import 