1. 데이터 전처리

In [17]:
from sklearn.datasets import load_iris
iris = load_iris()

In [18]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [20]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [21]:
feature_names = list(map(lambda s: s[:-5], iris.feature_names))
feature_names

['sepal length', 'sepal width', 'petal length', 'petal width']

In [23]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=feature_names)
df['target'] = iris.target #타겟컬럼 추가
df.head()

sepal length  sepal width  petal length  petal width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [24]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [25]:
import numpy as np
np.unique(iris.target, return_counts=True)

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

In [26]:
# # 디스크립션. 요약 필요한가?
# print(iris.DESCR) # key값에 있었어.
# df.describe() # 판다스 디스크라이브.


In [27]:
# 표를 봐야할 방식은. 분류 모델에 적합하게
df.groupby('target').describe()

sepal length                                             sepal width  \
              count   mean       std  min    25%  50%  75%  max       count   
target                                                                        
0              50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8        50.0   
1              50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0        50.0   
2              50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9        50.0   

               ... petal length      petal width                             \
         mean  ...          75%  max       count   mean       std  min  25%   
target         ...                                                            
0       3.428  ...        1.575  1.9        50.0  0.246  0.105386  0.1  0.2   
1       2.770  ...        4.600  5.1        50.0  1.326  0.197753  1.0  1.2   
2       2.974  ...        5.875  6.9        50.0  2.026  0.274650  1.4  1.8   

                       
        50%  75%  max  
target                 
0       0.2  0.3  0.6  
1       1.3  1.5  1.8  
2       2.0  2.3  2.5  

[3 rows x 32 columns]

In [28]:
# 박스 플롯 제거 및 


2. 학습세트 테스트세트 분리 # 값 균일하게 stratify=iris.target추가

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, stratify=iris.target ,test_size=0.2, random_state=2021
)

X_train.shape, X_test.shape, y_train.shape, y_test.shape
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([40, 40, 40], dtype=int64))

3. 학습 - 결정트리 사용

In [32]:
from sklearn.tree import DecisionTreeClassifier

In [33]:
dtc = DecisionTreeClassifier(random_state=2021)

In [34]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier(random_state=2021)

4. 예측

In [37]:
pred_dt = dtc.predict(X_test)
pred_dt


array([0, 1, 2, 2, 0, 1, 0, 1, 2, 0, 1, 1, 1, 2, 1, 0, 2, 0, 2, 0, 1, 2,
       0, 2, 1, 0, 1, 1, 2, 0])

In [39]:
res = pd.DataFrame({'y':y_test, 'DT' : pred_dt})
res.head()

y  DT
0  0   0
1  1   1
2  1   2
3  2   2
4  0   0

5. 평가







In [40]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred_dt)

In [42]:
acc
print(f'정확도(DT): {acc:.4f}')

정확도(DT): 0.9000


In [43]:
dtc.score(X_test, y_test)

0.9

In [44]:
# 서포트 벡터 머신 SVM 이용

In [46]:
# 3
from sklearn.svm import SVC
svc = SVC(random_state=2021)
svc.fit(X_train, y_train)

SVC(random_state=2021)

In [47]:
# 4
pred_sv = svc.predict(X_test)

In [49]:
# 어큐러시 스코어 모듈 이용해도 되고, SVC이용해도 정확도 결과는 같다
# 학습 fit, 예측, predict 등등 같다
svc.score(X_test, y_test)

0.9

In [53]:
# 로지스틱 회귀도 보자 # 결과가 이산적으로 도축. (그러나 회귀는 연속분포긴한다. )
# 로지스틱 회귀만 좀 더 공부할것

# 이름으로는 로지스틱 회귀 분류 가 더 어울려 LRC
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression(max_iter=500, random_state=2021)
lrc.fit(X_train, y_train)

LogisticRegression(max_iter=500, random_state=2021)

In [54]:
pred_lr=lrc.predict(X_test)

In [55]:
lrc.score(X_test, y_test)
# 정확도 자체는 좀더 높다. max_iter 과 관련있나?

0.9333333333333333

In [57]:
# 3모델 결과 비교 # 거의 비슷하나, 이번 수행은 0.933으로 로지스틱 회귀가 가장 높았다.
res['SV'] = pred_sv
res['LR'] = pred_lr
res

y  DT  SV  LR
0   0   0   0   0
1   1   1   1   1
2   1   2   1   1
3   2   2   2   2
4   0   0   0   0
5   1   1   1   1
6   0   0   0   0
7   1   1   1   1
8   2   2   2   2
9   0   0   0   0
10  1   1   1   1
11  1   1   1   1
12  1   1   1   1
13  2   2   1   2
14  2   1   1   1
15  0   0   0   0
16  2   2   2   2
17  0   0   0   0
18  2   2   2   2
19  0   0   0   0
20  1   1   1   1
21  2   2   2   2
22  0   0   0   0
23  2   2   2   2
24  2   1   1   1
25  0   0   0   0
26  1   1   1   1
27  1   1   1   1
28  2   2   2   2
29  0   0   0   0

In [58]:
# 참고사항으로 f - string 배움.